### ISSUE TITLE
Support blurhash for image previews

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/neon#2044] opened 2024-05-14 08:12 UTC
Since 28 (or maybe it was 29 idk) the WebDAV API exposes a blurhash string for images, so we could use it for showing a preview while still loading the actual preview or image itself.

**Comment by Leptopoda** [comment] 2024-05-15 10:02
dupe of https://github.com/nextcloud/neon/issues/1583

**Closed by Leptopoda** 2024-05-15 10:02 UTC
Labels: feature, package: neon_files

**Comment by provokateurin** [comment] 2024-05-15 10:10
Huh I searched for it because I was sure we had an issue for it, but the search didn't return anything :thinking:
